### ISSUE TITLE
use PODIO classes rather than `TTreeReader`

### ISSUE THREAD

**Issue by c-dilks** [eic/sidis-eic#153]
For `AnalysisEpic`, instead of using `TTreeReader` as we do with `AnalysisAthena`, use the PODIO-generated classes directly. This would allow us to take advantage of relations such as cluster/track matching:
```
edm4hep::ReconstructedParticle:
   OneToManyRelations:
      - edm4hep::Cluster               clusters     //clusters that have been used for this particle. 
```

- `AnalysisAthena` could be updated, if we want to try this approach now rather than waiting from output from the new JANA2-based framework (`EICrecon`)
- `AnalysisDelphes` and `AnalysisEcce` do not use PODIO upstream

**Comment by xinbaili** [comment]
That sounds cool! I believe it is to prepare for single simulation stack output analysis and `AnalysisJANA` gonna play a important role. Looking forward to it and will keep an eye on this.
