### ISSUE TITLE
ECCE production: are the cross sections correct for each Q2 range?

### ISSUE THREAD

**Issue by c-dilks** [eic/sidis-eic#181]
The latest `ECCE` stack production has the following directories:
```
                10x100-q2-high
                10x100-q2-low
                10x100
                18x275-Lambda
                18x275-q2-high
                18x275-q2-low
                18x275
                5x41-q2-low
                5x41
```
We need to be able to combine data from differing Q2 ranges together.
For `ATHENA`, this was straightforward since the directories specified the Q2 minimum in the name. For `ECCE`, however, there are three ranges:
1. `q2-low`: 1 < Q2 < 100
2. `q2-high`: 100 < Q2
3. general Q2 -- what is the minimum Q2? Assuming 1 for now, but is that right?

We need the correct cross sections for each of these. In #180 we added the following to `datarec/xsec/xsec.dat`, being careful to note the `FIXME` comment:
```bash
# Pythia 6, from ECCE production files:
# S3/eictest/ECCE/ProductionInputFiles/SIDIS/pythia6
# FIXME: there are no HEPMC files here, just ROOT files; since the generation
#        of this table requires HEPMC files (`s3tools/get-cross-section-ALL.sh`), for
#        now we just guess the cross section from the corresponding ATHENA Pythia 8
#        production above. These ECCE production files have Q2 maxima, unlike the
#        ATHENA HEPMC files; therefore, the cross sections may be a bit wrong here.
#label                     cross_section_[pb]  relative_uncertainty
pythia6:ep-5x41            4.0012e+05          0.00266   # general Q2
pythia6:ep-5x41-q2-low     4.0012e+05          0.00266   # 1 < Q2 < 100
pythia6:ep-10x100          5.5566e+05          0.00276   # general Q2
pythia6:ep-10x100-q2-low   5.5566e+05          0.00276   # 1 < Q2 < 100
pythia6:ep-10x100-q2-high  1343                0.0023    # 100 < Q2
pythia6:ep-18x275          7.4167e+05          0.00277   # general Q2
pythia6:ep-18x275-q2-low   7.4167e+05          0.00277   # 1 < Q2 < 100
pythia6:ep-18x275-q2-high  3370.2              0.00245   # 100 < Q2
```

Note that any changes to the Q2 minima values should also be updated in `s3tools/make-ecce-config.sh` in the following function:
```bash
# function to get the Q2 minimum, given subdir $1
function getQ2min {
  if   [[ "$1" =~ "q2-low"  ]]; then echo 1;
  elif [[ "$1" =~ "q2-high" ]]; then echo 100;
  else echo 1  # general Q2 # FIXME: is Q2min=1 correct?
  fi
}
```

**Comment by rseidl-rcf** [comment]
I will check the cross sections and update the table. We probably also need a similar table for the radcor files that exist at least on the generator level (and eventually also in produced form). In principle all of the originally eic-smear generated files have a TObjectString

**Comment by rseidl-rcf** [comment]
sorry, I did not want to close it, just comment.

I will check the cross sections and update the table (they are different - eg 18x275 high 3097, low 8.796e+5). The files without Q2 cut are indeed from 1 GeV upward. 
We probably also need a similar table for the radcor files that exist at least on the generator level (and eventually also in produced form). In principle all of the originally eic-smear generated files have a TObjectString crossSection, nEvents and nTrials in them but that did not get picked up in the full simulations.
