### ISSUE TITLE
Cross sections for the EPIC Pythia6 files

### ISSUE THREAD

**Issue by c-dilks** [eic/sidis-eic#211]
**Is your feature request related to a problem? Please describe.**
Q2 weighting for EPIC data is not correct, since we are currently using the old cross sections from ATHENA.

**Describe the solution you'd like**
- [x] Add cross sections to `datarec/xsec/xsec.dat` for the Pythia6 files we are using for EPIC.
  - Give them a unique name, and keep the old ones for backward compatibility. Something like `pythia6:10x100/Q2=10to100` would be fine.
- [ ] Update `s3tools/make-epic-config.sh` where `$crossSection` is set (this script might not yet be on the `main` branch)

**Comment by rseidl-rcf** [comment]
taken care of adding the cross sections to the temp.epic.ana branch, will take a look at the config.sh script

**Comment by c-dilks** [comment]
Thanks!

**Comment by c-dilks** [comment]
Today I learned they actually ran the Pythia8 files for `22.11.2`, so the config script will have to point to those instead. I will take care of this and validate the Q2 weighting. Of course we will eventually need your Pythia6 cross sections, for whenever those are run through the simulation.
