### ISSUE TITLE
Are the Pythia6 `hepmc` files afterburned?

### ISSUE THREAD

**Issue by c-dilks** [eic/sidis-eic#229]
Have the `hepmc` files in `S3/eictest/EPIC/EVGEN/SIDIS/pythia6/ep_${ENERGY}/hepmc_ip6/{,no}radcor/*.hepmc` been run through the afterburner? After #226 they will be the ones used for the `fastsim` CI checks.

**Comment by c-dilks** [comment]
@wdconinc or @rseidl-rcf do you happen to know?

**Comment by wdconinc** [comment]
There were two parallel directories and I copied the ones to S3 that seemed to have been afterburned. Check the first 20 lines of the hepmc3 file for the parameters.

**Comment by c-dilks** [comment]
Thanks, looks like the answer is yes.

**Comment by rseidl-rcf** [comment]
I see you have figured this out already, but yes, the hepmc_ip6 
directories did already apply the afterburner.
